//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Application_UberEats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Product
    {
        public int PId { get; set; }
        public int prod_id { get; set; }
        public int orderId { get; set; }
    }
}
