//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Application_UberEats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PId { get; set; }
        public string card_Name { get; set; }
        public string Card_Number { get; set; }
        public string CVV { get; set; }
        public int Id { get; set; }
    }
}
