//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Application_UberEats.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CustomerDbEntities : DbContext
    {
        public CustomerDbEntities()
            : base("name=CustomerDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Admin_Table> Admin_Table { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<tblRe> tblRes { get; set; }
        public virtual DbSet<Order_Product> Order_Product { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
    
        public virtual int GetRestaurantInformation()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetRestaurantInformation");
        }
    
        public virtual int Image_Procedure()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Image_Procedure");
        }
    
        public virtual ObjectResult<GetResInfo_Result> GetResInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetResInfo_Result>("GetResInfo");
        }
    
        public virtual ObjectResult<Procedure_Result> Procedure()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Procedure_Result>("Procedure");
        }
    
        public virtual ObjectResult<GetProductInfo_Result> GetProductInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductInfo_Result>("GetProductInfo");
        }
    
        public virtual ObjectResult<Procedure2_Result> Procedure2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Procedure2_Result>("Procedure2");
        }
    
        public virtual ObjectResult<getAllOrders_Result> getAllOrders()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAllOrders_Result>("getAllOrders");
        }
    }
}
